
package Ventana;


import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javax.swing.JPanel;


/**
 *
 * @author Arrecis
 */

public class Reloj extends javax.swing.JFrame {
    Letrero ver1,ver2,ver3;
    ImageIcon logo = new ImageIcon("umg.png");
    Calendar calendario = Calendar.getInstance();
    Calendar fecha = new GregorianCalendar();
    double grados=0,radianes=0, dato1=0,dato2=0,dato3=0;
    int hora = fecha.get(Calendar.HOUR_OF_DAY);
    int minuto = fecha.get(Calendar.MINUTE);
    int segundo = fecha.get(Calendar.SECOND);
   
       
    
    //300,100  // 200  300  // 400 300
    //209 282 200 300 220 300
    //169,300 633 300 401 60
    int [] posX = {259,653,461};
    int [] posY=  {200,200,50};
    /**
     * Creates new form Reloj
     */
    public Reloj() {
        segundo = calendario.get(Calendar.SECOND);
        //System.out.println("segu "+segundo);
        this.setContentPane(new Lienzo());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        initComponents();
        umg.setIcon((new ImageIcon(logo.getImage().getScaledInstance(umg.getWidth(),umg.getHeight(),Image.SCALE_SMOOTH ))));
        this.setResizable(false);
        this.setTitle("Programación ll");
        panel.setSize(950,800);
        this.setSize(950,800);
        this.setLocationRelativeTo(null);
        
        letras();
        
    }
    
    public void letras(){
    
        try{
            
           ver1 = new Letrero("La Florida",1000,this.texto1, this.letra);
           ver1.start();
           ver2 = new Letrero("Universida Mariano Galvez",1000,this.texto2, this.letras2);
           ver2.start();
           ver3 = new Letrero("Steven Arrecis 3590-20-285",1000,this.textos3, this.letras3);
           ver3.start();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "btnH1Iniciar(). " + ex.getMessage());
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        texto1 = new javax.swing.JLabel();
        letra = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        letras2 = new javax.swing.JLabel();
        umg = new javax.swing.JLabel();
        textos3 = new javax.swing.JLabel();
        letras3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(texto1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        letra.setText("jLabel1");

        texto2.setText("jLabel1");

        letras2.setText("jLabel1");

        umg.setText("jLabel1");

        textos3.setText("jLabel1");

        letras3.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textos3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letras2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(letra)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letras3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(umg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(umg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textos3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letras2)
                    .addComponent(letras3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reloj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel letra;
    private javax.swing.JLabel letras2;
    private javax.swing.JLabel letras3;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel textos3;
    private javax.swing.JLabel umg;
    // End of variables declaration//GEN-END:variables

 public class Lienzo extends JPanel{
     
    @Override
    public void paint (Graphics g){
        super.paint(g);
        Graphics2D dibuja = (Graphics2D)g;
        
        dibuja.setColor(Color.GREEN);
        dibuja.fillPolygon(posX, posY, 3); //dibujamos el triangulo
        
        dibuja.setColor(Color.BLACK);
        dibuja.fillRect(365,125, 180, 40); // dibujamos el cuadrado
              
        dibuja.setColor(Color.BLUE);
        dibuja.fillRect(300,200, 320, 220); // dibujamos el cuadrado
        dibuja.setColor(Color.BLACK);
        dibuja.fillOval(350,200,220,220); // dibujamos el circulo GRANDE
        
        dibuja.setColor(Color.white);
        dibuja.fillOval(360,210,200,200); // dibujamos el circulo
       
        dibuja.setColor(Color.BLACK);
        dibuja.fillOval(445,298,20,20); // dibujamos el punto en el centro del circulo
        dibuja.setColor(Color.BLUE);
        dibuja.fillRect(300,420, 320, 290); // dibujamos el cuadrado
        dibuja.setColor(Color.white);
        dibuja.fillRect(320,450, 280, 240); // dibujamos el cuadrad
        dibuja.setColor(Color.orange);
        dibuja.fillRect(445,453 ,20, 140);
        dibuja.setColor(Color.BLACK);
        dibuja.fillOval(435,448,40,40); // dibujamos el punto en el centro del circulo
        dibuja.setColor(Color.BLACK);
        dibuja.fillOval(428,588,60,60); // dibujamos el punto en el centro del circulo
        
        Font myFont = new Font ("Courier New", 1, 20);
        dibuja.setFont(myFont);
        dibuja.setColor(Color.BLACK);
        dibuja.drawString("XII",440,226); //numero 12
        dibuja.drawString("I",505,243); // numero 1
        dibuja.drawString("II",520,275); // numero 2
        dibuja.drawString("III",515,315); // numero 3
        dibuja.drawString("IV",520,355); // numero 4
        dibuja.drawString("V",495,395); // numero 5
        dibuja.drawString("VI",445,408); // numero 6
        dibuja.drawString("VII",400,390); // numero 7
        dibuja.drawString("VIII",370,355); // numero 8
        dibuja.drawString("IX",360,315); // numero 9
        dibuja.drawString("X",373,275); // numero 10
        dibuja.drawString("XI",397,243); // numero 11
        

        Hora hilo = new Hora(dibuja);
        hilo.start();
//        Pendulo hilo2 = new Pendulo(dibuja);
//        hilo2.start();
        repaint();  
    }
  }
}
